### ISSUE TITLE
Version 0.4.1+pre1  does not install examples.

### ISSUE THREAD

**Issue by EmmanuelPil** [Calsign/APDE#42] opened 2018-05-21 18:46 UTC
Not that it is that important, but neither can you re-download the eamples in the settings.
The library examples are installed correctly.

**Comment by Calsign** [comment] 2018-05-24 03:01
@EmmanuelPil Are you connected to Wi-Fi? By default examples only download when on Wi-Fi. Do you get an error message in the console? Do you see a message such as "Examples have been updated"?

I can't reproduce this on my phone - examples download fine for me. This is very strange because I didn't change anything about the examples in the latest release.

**Comment by EmmanuelPil** [comment] 2018-05-24 12:10
Yes, using Wiifi. It happened with the last version.  I deleted and re-installed  the app several times, but examples are not installed, neither can be re-downloaded. I am using KitKat 4.4  on a Samsung Tab E 9.6  tablet. It gives message on the status bar that examples are uploaded, but the aren't dew to error in cosole

> org.eclipse.jgit.api.errors.TransportException: https://github.com/Calsign/APDE-Examples-Repo.git: cannot open git-upload-pack
> 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:223)
> 	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
> 	at com.calsignlabs.apde.vcs.GitRepository.canPull(GitRepository.java:195)
> 	at com.calsignlabs.apde.APDE$3.run(APDE.java:883)
> 	at java.lang.Thread.run(Thread.java:841)
> Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/Calsign/APDE-Examples-Repo.git: cannot open git-upload-pack
> 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:524)
> 	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309)
> 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:202)
> 	... 4 more
> Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6c2511a0: Failure in SSL library, usually a protocol error
> error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x6894dec8:0x00000000)
> 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
> 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
> 	at com.android.okhttp.Connection.connect(Connection.java:107)
> 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
> 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
> 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
> 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
> 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
> 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
> 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
> 	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98)
> 	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:168)
> 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:475)
> 	... 6 more
> Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6c2511a0: Failure in SSL library, usually a protocol error
> error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x6894dec8:0x00000000)
> 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
> 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
> 	... 18 more
>

**Comment by Calsign** [comment] 2018-05-25 03:08
@EmmanuelPil Just to be clear, the examples were downloaded correctly in v0.4.0 on the same phone?

The error seems to be the same one described in [this StackOverflow post](https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han), a bug in Android 4.4 and below. I don't understand why the issue would just appear now, though, if it affects all Android 4.4 devices, unless this is your first time installing the app on this device.

**Comment by Calsign** [comment] 2018-05-25 03:37
@EmmanuelPil I can confirm this bug in a 4.4 emulator. I don't know how I didn't find this before, but I should be able to fix it now.

**Comment by Calsign** [comment] 2018-05-25 04:52
This should be fixed with 6c62c4f. I will leave it open until I get confirmation from you.

Please check out this bugfix APK to see if it solves the problem. It is just 0.4.1-pre2 with the bugfix:

https://www.dropbox.com/s/okkwhv3oji7p8tf/APDE-bugfix-2018-05-25.apk?dl=0

If all goes well I intend to (finally) roll out 0.4.1 to the main channel.

**Comment by EmmanuelPil** [comment] 2018-05-25 15:51
Yes, this fix installed the  files correctly, and also re-download without any error.
Thanks for the real quick fix!
PS Yes I used the versions on the same device.

**Closed** 2018-05-25 17:54 UTC
Labels: bug
