### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by ekg** [Calsign/APDE#17] opened 2016-01-31 18:04 UTC
I have allowed installation from unknown sources. Yet, when I run a sketch I am presented with an install dialog in which I simply can't press the install button. I can press only cancel. Does anyone have any idea what might be going on?

**Comment by Calsign** [comment] 2016-01-31 18:22
This is a known issue. I presume that you are using Twilight or some similar app to dim your screen. The problem is that these screen dimmers draw over the entire screen and, for security reasons, Google disables the "install" button when other applications are drawing over the screen. See [this forum post](http://androidforums.com/threads/why-cant-i-click-install-with-apk.708801/) for more information.

Therefore, to install APDE sketches, you must temporarily disable your screen dimmer. You should look to see if there are settings to disable it in certain apps. Note that the installer dialog is actually the Android system, not APDE.

**Comment by Calsign** [comment] 2017-01-21 21:46
This issue has been fixed with commit 39db5548a070315cebb8dde9f2bcf6354a23207a (actually several months ago) and the change found its way into v0.4.0, which is now fully rolled out.

There is also an [FAQ entry](https://github.com/Calsign/APDE/wiki#why-cant-i-press-the-install-button) for this issue which links to a detailed Wiki article about the issue.

This problem and its solution/workaround appear to be well-documented, so I am closing this issue.

**Closed by Calsign** 2017-01-21 21:46 UTC
