### ISSUE TITLE
Sketch sometimes clears after turning the screen off and on

### ISSUE THREAD

**Issue by liquid600pgm** [Calsign/APDE#40] opened 2018-05-16 16:20 UTC
Hello,

I have experienced this issue numerous times now. I have written a review on Google Play - no fix, but then I noticed this repo.

Anyways, sometimes when I turn my screen off for a break, and then turn the screen back on, the sketch's code is just cleared. It is really frustrating, because I sometimes make large sketches and then suddenly all my code is gone.

**Comment by Calsign** [comment] 2018-05-16 19:08
Sorry about this.

This is a duplicate of #24. Please check out that issue and try installing the preview release from the [preview channel](https://plus.google.com/communities/117703520591262292626), that should fix the issue.

**Closed by Calsign** 2018-05-16 19:08 UTC
Labels: bug, duplicate
