### ISSUE TITLE
Crash on ketai library import

### ISSUE THREAD

**Issue by Tenns** [Calsign/APDE#68] opened 2019-04-12 14:42 UTC
When installing a compressed library, such as ketai, the apde app crashes.

**Comment by Calsign** [comment] 2019-04-15 04:48
This is a duplicate of #38 (and maybe others).

Please try [manual installation](https://github.com/Calsign/APDE/wiki/Installing-Contributed-Libraries#manual-installation). If this doesn't work, I am happy to assist you further in this thread.

**Closed by Calsign** 2019-04-15 04:48 UTC
Labels: duplicate, question
